### ISSUE TITLE
Bug: cannot repay usdc debt

### ISSUE THREAD

**Issue by jo-chemla** [Ricochet-Exchange/rex-bank-frontend#5]
Hi there, I've tried repaying my debt for the past hour and never managed to do so. I hit the repay max button, which auto-fills 45.45 USDCx to repay, and when submitting the transaction, metamask shows an error message like the following screenshot. Then a metamask alert shows an error stating "replacement transactino underpriced (code 32603)". I tried with lower debt to repay (45.40, 45 etc), and higher gas (30, 35), with no luck. 

![image](https://user-images.githubusercontent.com/16822841/141752514-a484cd27-2b3b-4940-a819-248319f93a8e.png)

**Comment by mikeghen** [comment]
@jo-chemla, I see the issue, `replacement transactino underpriced (code 32603)` means you have a pending transaction with the same nonce that's still pending, the 0.6 matic must be an issue, I just borrowed and repaid on the old bank and it went through just fine, that "replacement transaction" error is a network error, not a contract error.
